"""adding directions

Revision ID: 80997cd240df
Revises: 4f31cb1692df
Create Date: 2020-06-11 19:15:54.744033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80997cd240df'
down_revision = '4f31cb1692df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('directions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'directions')
    # ### end Alembic commands ###
