"""create-route

Revision ID: f29fe2de47bc
Revises: 15e2397de46e
Create Date: 2020-06-08 20:01:35.963355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29fe2de47bc'
down_revision = '15e2397de46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('average_time', sa.Integer(), nullable=True),
    sa.Column('best_time', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
