"""add rating to runs

Revision ID: 7831df48c71f
Revises: c83d5c808d7c
Create Date: 2020-07-14 14:09:15.141797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7831df48c71f'
down_revision = 'c83d5c808d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'rating')
    # ### end Alembic commands ###
